dependencies:
- name: exposecontroller
  version: 2.3.85
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.85
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- alias: fecache
  name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 5.3.0
